version: '3.7'

services:
    php-base:
        build: services/php-base

    builder:
        build: services/builder
        depends_on:
            - postgres
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/app:cached"
            - "~/.composer/cache:/home/app/.composer/cache"
