version: '3'

volumes:
    mysql-data: {}

services:
    php-base:
        build: services/php-base
        image: "${PROJECT_NAME}_basephp"
        labels:
            - "traefik.enable=false"

    router:
        build: services/router
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        # # Use network alias if you need to access a container via a specific
        # # host by using the routing from another container
        # networks:
        #     default:
        #         aliases:
        #             - api.app.test
        labels:
            - "traefik.enable=false"

    frontend:
        build: services/frontend
        depends_on:
            - mysql
        volumes:
            - "../../${PROJECT_DIRECTORY}:/var/www:cached"
        labels:
            - "traefik.port=80"
            - "traefik.frontend.entryPoints=https"
            - "traefik.frontend.rule=Host:${PROJET_HOSTNAMES}"

    mysql:
        build: services/mysql
        volumes:
            - "mysql-data:/var/lib/mysql"
        labels:
            - "traefik.enable=false"

    builder:
        build: services/builder
        depends_on:
            - mysql
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/app:cached"
            - "~/.composer/cache:/home/app/.composer/cache"
        labels:
            - "traefik.enable=false"
